### ISSUE TITLE
Add getGithubFileHash Function

### ISSUE THREAD

**Issue by jamesward** [jamesward/github-files#2]
Add a function that allows you to get a blob's hash just by specifying a branch and a file name (for when you always want the most recent instead of a specific version of a blob).

Proposed API:

```
$.getGithubFileHash(user, repo, file, callback, branch)
```

Where `branch` is optional (defaulting to `master/HEAD`).  The `callback` function will probably just need to have a string parameter that will contain the hash.

**Comment by brntbeer** [comment]
Oops! Just now noticed this issue. It seems my pull request is a great middle ground for this for the time being? 

more than happy to continue discussion over on #4 if need be!

**Comment by jamesward** [comment]
I'm considering this closed thanks to @brntbeer!
