### ISSUE TITLE
Inconsistently working

### ISSUE THREAD

**Issue by ethanspitz** [jamesward/github-files#5]
I have the code implemented, but sometimes it loads the code, and sometimes it doesn't load anything.

**Comment by jamesward** [comment]
Hmmm...  That is not good.  Can you provide the steps to reproduce or more information about the problem?  Is GitHub's API always returning the content?

**Comment by ethanspitz** [comment]
I'm not quite sure how to reproduce it, while I was developing my webpage using it, there would be like 30 minute periods where it seemed to pull nothing. I don't know much about GitHub's API as I've never used it before, right now it is working, but I have no way of predicting when it will stop working.

Here is the page I was using that it was working inconsistantly on: http://ethanspitz.com/stage/

**Comment by jamesward** [comment]
This could be you hitting the API limits on GitHub:
http://developer.github.com/v3/#rate-limiting

Think that is possible?

**Comment by ethanspitz** [comment]
It's possible, but not probable. It seems to be happening right after I make a push to the repo I'm trying to read from. I'm thinking it is on GitHub's end not the code's

**Comment by jamesward** [comment]
If you happen to have a network monitor (like Chrome Dev Tools) open when it happens, then you can check out the response from GitHub and see if the problem is on their side or the `github-files` side.

**Comment by ethanspitz** [comment]
It is the rate limit (just spammed refresh) "API Rate Limit Exceeded for [insert my ip here]"

**Comment by jamesward** [comment]
Luckily that is just for your IP.  So your users should be ok unless they very frequently refresh the page.  :)

Should I close this?

**Comment by ethanspitz** [comment]
Well the only thing I did notice is when I showed my friends, they saw the same message, but when I VPN'd into another country and just viewed my page, it worked fine. I think you can probably close this, it's not on the github-files side.

**Comment by jamesward** [comment]
Cool.  Let me know if there is anything else I can help with.
